const stays = [
  { id: 1, name: 'The Courtyard House', city: 'Jaipur', area: 'Malviya Nagar', college: 'MNIT Jaipur', rent: 12500, rating: 4.9, distance: '0.8 km', room: 'Single', tags: ['Wi-Fi', 'Food', 'Laundry'], verified: true, newest: 6, image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=900&q=85', about: 'A bright, calm home with a leafy courtyard and easy access to MNIT.' },
  { id: 2, name: 'Mango Tree Living', city: 'Jaipur', area: 'Vaishali Nagar', college: 'Amity University', rent: 8500, rating: 4.7, distance: '1.2 km', room: 'Double', tags: ['Wi-Fi', 'Study table', 'Power backup'], verified: true, newest: 12, image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=85', about: 'Friendly shared living with sunny rooms, fast Wi-Fi and flexible meal plans.' },
  { id: 3, name: 'Aravali Student Homes', city: 'Jaipur', area: 'Jagatpura', college: 'Manipal University', rent: 15000, rating: 4.8, distance: '0.5 km', room: 'Single', tags: ['AC', 'Food', 'Gym'], verified: true, newest: 3, image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=85', about: 'Modern student rooms just across from campus, with community spaces to unwind.' },
  { id: 4, name: 'Blue City Nest', city: 'Jodhpur', area: 'Ratanada', college: 'JNVU', rent: 7200, rating: 4.6, distance: '0.9 km', room: 'Triple', tags: ['Wi-Fi', 'Food', 'Security'], verified: true, newest: 9, image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=85', about: 'A welcoming, budget-friendly stay in the heart of Jodhpur student life.' },
  { id: 5, name: 'Mehrangarh House', city: 'Jodhpur', area: 'Paota', college: 'IIT Jodhpur', rent: 11000, rating: 4.8, distance: '1.5 km', room: 'Double', tags: ['AC', 'Laundry', 'Parking'], verified: true, newest: 2, image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=85', about: 'Quiet, well-connected rooms with generous common areas and an attentive owner.' },
  { id: 6, name: 'Suncatcher PG', city: 'Jodhpur', area: 'Chopasni Road', college: 'NIFT Jodhpur', rent: 9500, rating: 4.5, distance: '1.1 km', room: 'Single', tags: ['Wi-Fi', 'Study table', 'Housekeeping'], verified: false, newest: 1, image: 'https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=900&q=85', about: 'A relaxed, independent stay for students who like their own rhythm.' },
  { id: 7, name: 'Neem Grove Residency', city: 'Jaipur', area: 'Pratap Nagar', college: 'JECRC University', rent: 6800, rating: 4.6, distance: '0.7 km', room: 'Triple', tags: ['Wi-Fi', 'Food', 'Security'], verified: true, newest: 5, image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=85', about: 'Affordable, secure rooms with a friendly community near JECRC University.' },
  { id: 8, name: 'Pink City Commons', city: 'Jaipur', area: 'C-Scheme', college: 'Rajasthan University', rent: 13500, rating: 4.8, distance: '1.0 km', room: 'Double', tags: ['AC', 'Laundry', 'Housekeeping'], verified: true, newest: 4, image: 'https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=900&q=85', about: 'A thoughtfully designed shared home close to cafes, libraries, and campus.' },
  { id: 9, name: 'Jaswant House', city: 'Jodhpur', area: 'Sardarpura', college: 'JNVU', rent: 8800, rating: 4.7, distance: '0.6 km', room: 'Double', tags: ['Wi-Fi', 'Study table', 'Power backup'], verified: true, newest: 7, image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=85', about: 'A bright Sardarpura stay with study-ready rooms and reliable power backup.' },
  { id: 10, name: 'Mandore Student Lodge', city: 'Jodhpur', area: 'Mandore Road', college: 'IIT Jodhpur', rent: 6200, rating: 4.4, distance: '1.8 km', room: 'Triple', tags: ['Food', 'Parking', 'Security'], verified: false, newest: 8, image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=900&q=85', about: 'A quiet, value-focused lodge with meals and spacious shared rooms.' },
  { id: 11, name: 'Blue Door Studios', city: 'Jaipur', area: 'Mansarovar', college: 'Poornima University', rent: 10200, rating: 4.7, distance: '1.3 km', room: 'Single', tags: ['AC', 'Wi-Fi', 'Study table'], verified: true, newest: 10, image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=85', about: 'Independent rooms for focused students, with a calm study lounge.' },
  { id: 12, name: 'Desert Bloom PG', city: 'Jodhpur', area: 'Shastri Nagar', college: 'NIFT Jodhpur', rent: 7800, rating: 4.6, distance: '0.9 km', room: 'Single', tags: ['Wi-Fi', 'Food', 'Laundry'], verified: true, newest: 11, image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=85', about: 'A warm, welcoming PG with homemade meals and an easy commute to NIFT.' },
  { id: 13, name: 'Hawa Mahal Homes', city: 'Jaipur', area: 'Bani Park', college: 'Rajasthan University', rent: 7600, rating: 4.5, distance: '1.4 km', room: 'Double', tags: ['Wi-Fi', 'Food', 'Security'], verified: true, newest: 13, image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=85', about: 'A central Jaipur home with easy bus links and a relaxed shared courtyard.' },
  { id: 14, name: 'Moti Dungri House', city: 'Jaipur', area: 'Adarsh Nagar', college: 'Rajasthan University', rent: 11800, rating: 4.7, distance: '0.9 km', room: 'Single', tags: ['AC', 'Wi-Fi', 'Laundry'], verified: true, newest: 14, image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=85', about: 'Comfortable private rooms near campus, markets, and daily essentials.' },
  { id: 15, name: 'Campus Corner PG', city: 'Jaipur', area: 'Tonk Road', college: 'JECRC University', rent: 5900, rating: 4.3, distance: '1.1 km', room: 'Triple', tags: ['Food', 'Power backup', 'Parking'], verified: false, newest: 15, image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=900&q=85', about: 'A practical, budget-first stay with generous rooms and daily meals.' },
  { id: 16, name: 'Rangrez Residency', city: 'Jaipur', area: 'Durgapura', college: 'Manipal University', rent: 14500, rating: 4.9, distance: '0.6 km', room: 'Single', tags: ['AC', 'Food', 'Housekeeping'], verified: true, newest: 16, image: 'https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=900&q=85', about: 'Premium student living with thoughtful service and a quiet work lounge.' },
  { id: 17, name: 'Rao Hostel House', city: 'Jodhpur', area: 'Residency Road', college: 'JNVU', rent: 6900, rating: 4.4, distance: '1.0 km', room: 'Triple', tags: ['Wi-Fi', 'Food', 'Housekeeping'], verified: true, newest: 17, image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=85', about: 'A friendly hostel with reliable meals and a lively student community.' },
  { id: 18, name: 'Fort View Living', city: 'Jodhpur', area: 'Nai Sarak', college: 'IIT Jodhpur', rent: 12800, rating: 4.8, distance: '1.2 km', room: 'Single', tags: ['AC', 'Wi-Fi', 'Study table'], verified: true, newest: 18, image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=85', about: 'Light-filled rooms with a focused study setup and beautiful old-city views.' },
  { id: 19, name: 'Sunset Square', city: 'Jodhpur', area: 'Kudi Bhagtasni', college: 'NIFT Jodhpur', rent: 8200, rating: 4.5, distance: '1.4 km', room: 'Double', tags: ['Wi-Fi', 'Parking', 'Security'], verified: false, newest: 19, image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=85', about: 'A bright and secure shared home with easy access to NIFT.' },
  { id: 20, name: 'Umaid Study House', city: 'Jodhpur', area: 'Chopasni Housing Board', college: 'IIT Jodhpur', rent: 10400, rating: 4.7, distance: '0.8 km', room: 'Double', tags: ['AC', 'Laundry', 'Power backup'], verified: true, newest: 20, image: 'https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=900&q=85', about: 'Calm, study-friendly rooms with dependable power and laundry service.' }
];

const extraHostels = [
  ['IIT Heights', 'Jodhpur', 'Karwar', 'IIT Jodhpur', 8900, 'Double'], ['Blue Fort Residency', 'Jodhpur', 'Pal Road', 'IIT Jodhpur', 9800, 'Triple'], ['Campus Gate Hostel', 'Jodhpur', 'Shikargarh', 'IIT Jodhpur', 11500, 'Single'], ['Scholar Square', 'Jodhpur', 'Banar Road', 'IIT Jodhpur', 7600, 'Double'], ['The Study Nook', 'Jodhpur', 'Pal Gaon', 'IIT Jodhpur', 8400, 'Triple'],
  ['JNVU Corner House', 'Jodhpur', 'Ratanada', 'JNVU', 7400, 'Double'], ['Sardarpura Student Inn', 'Jodhpur', 'Sardarpura', 'JNVU', 9200, 'Single'], ['Heritage Boys Hostel', 'Jodhpur', 'Paota', 'JNVU', 6500, 'Triple'], ['NIFT Walk Hostel', 'Jodhpur', 'Shastri Nagar', 'NIFT Jodhpur', 8700, 'Double'], ['Designers Den', 'Jodhpur', 'Chopasni Road', 'NIFT Jodhpur', 10800, 'Single'],
  ['MNIT Gate PG', 'Jaipur', 'Malviya Nagar', 'MNIT Jaipur', 9800, 'Double'], ['Campus View Jaipur', 'Jaipur', 'Malviya Nagar', 'MNIT Jaipur', 13200, 'Single'], ['Sanganer Road Hostel', 'Jaipur', 'Durgapura', 'MNIT Jaipur', 7200, 'Triple'], ['JECRC Junction', 'Jaipur', 'Pratap Nagar', 'JECRC University', 6500, 'Double'], ['University View PG', 'Jaipur', 'Sitapura', 'JECRC University', 8200, 'Single'],
  ['Manipal Mile Hostel', 'Jaipur', 'Jagatpura', 'Manipal University', 9200, 'Double'], ['Jagatpura Girls Home', 'Jaipur', 'Jagatpura', 'Manipal University', 11800, 'Single'], ['Poornima Park PG', 'Jaipur', 'Mansarovar', 'Poornima University', 7000, 'Triple'], ['Mansarovar Study Stay', 'Jaipur', 'Mansarovar', 'Poornima University', 9600, 'Double'], ['University Road Hostel', 'Jaipur', 'Bani Park', 'Rajasthan University', 8900, 'Single'],
  ['Pink City Girls Hostel', 'Jaipur', 'Adarsh Nagar', 'Rajasthan University', 7800, 'Double'], ['Central Jaipur Hostel', 'Jaipur', 'C-Scheme', 'Rajasthan University', 10500, 'Triple'], ['Raja Park Student House', 'Jaipur', 'Raja Park', 'Rajasthan University', 12000, 'Single'], ['Vaishali Campus PG', 'Jaipur', 'Vaishali Nagar', 'Amity University', 8600, 'Double'], ['Amity Road Hostel', 'Jaipur', 'Vaishali Nagar', 'Amity University', 6900, 'Triple'],
  ['Kudi Student Rooms', 'Jodhpur', 'Kudi Bhagtasni', 'NIFT Jodhpur', 7300, 'Triple'], ['Umaid Girls Hostel', 'Jodhpur', 'Shastri Nagar', 'NIFT Jodhpur', 10100, 'Single'], ['Paota Shared Living', 'Jodhpur', 'Paota', 'JNVU', 8100, 'Double'], ['Ratanada Residency', 'Jodhpur', 'Ratanada', 'JNVU', 6800, 'Triple'], ['Jodhpur Student Square', 'Jodhpur', 'Nai Sarak', 'IIT Jodhpur', 10600, 'Single'],
  ['MNIT Sunrise PG', 'Jaipur', 'Malviya Nagar', 'MNIT Jaipur', 9000, 'Triple'], ['Maitri Girls PG', 'Jaipur', 'Malviya Nagar', 'MNIT Jaipur', 11500, 'Double'], ['Hostel 36 Malviya', 'Jaipur', 'Malviya Nagar', 'MNIT Jaipur', 7800, 'Triple'], ['Orbit Student House', 'Jaipur', 'Malviya Nagar', 'MNIT Jaipur', 12800, 'Single'], ['Green Door PG', 'Jaipur', 'Malviya Nagar', 'MNIT Jaipur', 10400, 'Double']
].forEach((item, index) => stays.push({ id: 21 + index, name: item[0], city: item[1], area: item[2], college: item[3], rent: item[4], rating: 4.3 + ((index * 7) % 7) / 10, distance: `${(0.6 + (index % 6) * 0.3).toFixed(1)} km`, room: item[5], tags: index % 2 ? ['Wi-Fi', 'Security', 'Study table'] : ['Wi-Fi', 'Food', 'Laundry'], verified: index % 4 !== 3, newest: 21 + index, image: `https://images.unsplash.com/photo-${['1555854877-bab0e564b8d5', '1522708323590-d24dbb6b0267', '1505693416388-ac5ce068fe85', '1560185008-b033106af5c3'][index % 4]}?auto=format&fit=crop&w=900&q=85`, about: `A student-focused ${item[5].toLowerCase()} sharing hostel near ${item[3]}.` }));

const realHostelPhotos = [
  'photo-1555854877-bab0e564b8d5', 'photo-1522708323590-d24dbb6b0267', 'photo-1505693416388-ac5ce068fe85', 'photo-1560185008-b033106af5c3', 'photo-1493809842364-78817add7ffb', 'photo-1560448204-e02f11c3d0e2', 'photo-1564013799919-ab600027ffc6', 'photo-1571896349842-33c89424de2d', 'photo-1505693416388-ac5ce068fe85', 'photo-1560185008-b033106af5c3', 'photo-1484154218962-a197022b5858', 'photo-1524758631624-e2822e304c36', 'photo-1497366811353-6870744d04b2', 'photo-1497366754035-f200968a6e72', 'photo-1521737711867-e3b97375f902', 'photo-1540518614846-7eded433c457', 'photo-1564078516393-cf04bd966897', 'photo-1560185127-6a8c8f7d1b0c', 'photo-1598928506311-c55ded91a20c', 'photo-1618220179428-22790b461013', 'photo-1616486338812-3dadae4b4ace', 'photo-1600210492486-724fe5c67fb0', 'photo-1615874694520-474822394e73', 'photo-1600607687939-ce8a6c25118c', 'photo-1600566753190-17f0baa2a6c3'
].map(photo => `https://images.unsplash.com/${photo}?auto=format&fit=crop&w=900&q=85`);
stays.forEach((stay, index) => { stay.image = realHostelPhotos[index % realHostelPhotos.length]; });
const savedAdminEdits = JSON.parse(localStorage.getItem('hostelhive-admin-edits') || 'null');
if (savedAdminEdits) savedAdminEdits.forEach(savedStay => { const stay = stays.find(item => item.id === savedStay.id); if (stay) Object.assign(stay, savedStay); });
localStorage.setItem('hostelhive-properties', JSON.stringify(stays));

const collegeFilter = document.createElement('label');
collegeFilter.innerHTML = '<span>Near college</span><select id="collegeSelect"><option value="all">Any college</option><option>IIT Jodhpur</option><option>JNVU</option><option>NIFT Jodhpur</option><option>MNIT Jaipur</option><option>JECRC University</option><option>Manipal University</option><option>Rajasthan University</option><option>Poornima University</option><option>Amity University</option></select>';
document.querySelector('#budgetSelect').closest('label').before(collegeFilter);
const searchLayoutStyle = document.createElement('style');
searchLayoutStyle.textContent = '.search-form{grid-template-columns:1fr 1.55fr 1fr 1fr 1fr auto}@media(max-width:850px){.search-form{grid-template-columns:1fr 1fr}.search-form .wide{grid-column:span 2}}@media(max-width:550px){.search-form{grid-template-columns:1fr}.search-form .wide{grid-column:auto}}.admin-fields{display:grid;grid-template-columns:1fr 1fr;gap:11px}.admin-preview{height:150px;border-radius:5px;background-size:cover;background-position:center;border:1px solid var(--line)}@media(max-width:550px){.admin-fields{grid-template-columns:1fr}}';
document.head.append(searchLayoutStyle);
document.querySelector('.hero-stats strong').textContent = `${stays.length}+`;

let activeGender = 'all';
stays.forEach((stay, index) => { stay.gender = index % 3 === 0 ? 'Female' : index % 3 === 1 ? 'Male' : 'Unisex'; });

let saved = JSON.parse(localStorage.getItem('hostelhive-saved') || '[]');
let bookings = JSON.parse(localStorage.getItem('hostelhive-bookings') || '[]');
const grid = document.querySelector('#stayGrid');
const count = document.querySelector('#resultCount');
const empty = document.querySelector('#emptyState');
const toast = document.querySelector('#toast');

function money(value) { return `₹${value.toLocaleString('en-IN')}`; }

function render(list = stays) {
  count.textContent = `Showing ${list.length} stays`;
  empty.hidden = list.length > 0;
  grid.innerHTML = list.map(stay => `<article class="stay-card"><div class="stay-image" style="background-image:url('${stay.image}')"><span class="badge">${stay.verified ? '● VERIFIED' : 'NEW THIS WEEK'}</span><button class="heart ${saved.includes(stay.id) ? 'saved' : ''}" data-save="${stay.id}" aria-label="Save ${stay.name}">${saved.includes(stay.id) ? '♥' : '♡'}</button></div><div class="stay-info"><div class="stay-title"><div><small class="listing-type">${stay.room === 'Single' ? 'STUDENT PG' : 'STUDENT HOSTEL'}</small><h3>${stay.name}</h3></div><span class="rating">★ ${stay.rating}</span></div><div class="stay-location">${stay.area}, ${stay.city} · ${stay.distance} to ${stay.college}</div><div class="stay-meta">${stay.tags.map(tag => `<span>${tag}</span>`).join('')}<span>${stay.room} sharing</span></div><div class="stay-bottom"><div class="price"><strong>${money(stay.rent)}</strong><small>per month · deposit varies</small></div><button class="view-btn" data-view="${stay.id}">See hostel →</button></div></div></article>`).join('');
  document.querySelector('#savedCount').textContent = saved.length;
}

function filter() {
  const city = document.querySelector('#citySelect').value;
  const query = document.querySelector('#queryInput').value.toLowerCase();
  const budget = document.querySelector('#budgetSelect').value;
  const room = document.querySelector('#roomSelect').value;
  const college = document.querySelector('#collegeSelect').value;
  const sort = document.querySelector('#sortSelect').value;
  let list = stays.filter(stay => (city === 'all' || stay.city === city) && (college === 'all' || stay.college === college) && (!query || `${stay.name} ${stay.area} ${stay.college} ${stay.city}`.toLowerCase().includes(query)) && (budget === 'all' || stay.rent <= Number(budget)) && (room === 'all' || stay.room === room) && (activeGender === 'all' || stay.gender === activeGender));
  if (sort === 'price-low') list.sort((a, b) => a.rent - b.rent);
  if (sort === 'price-high') list.sort((a, b) => b.rent - a.rent);
  if (sort === 'rating') list.sort((a, b) => b.rating - a.rating);
  if (sort === 'newest') list.sort((a, b) => a.newest - b.newest);
  render(list);
}

function notify(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2500); }
function openModal(html) { document.querySelector('#modalContent').innerHTML = html; document.querySelector('#modalBackdrop').hidden = false; }
function showAdminLogin() { openModal('<div class="kicker">Restricted access</div><h2>Admin login.</h2><p>Sign in with your HostelHive administrator email to manage hostels and bookings.</p><form class="modal-form" id="adminLoginForm"><input name="email" type="email" placeholder="Admin email address" required><input name="password" type="password" minlength="6" placeholder="Password" required><button class="dark-btn">Open admin dashboard ↗</button></form>'); }
function showAdminDashboard() { const pending = bookings.filter(booking => booking.status === 'Pending').length; openModal(`<div class="admin-dashboard"><div class="eyebrow">HostelHive admin</div><div class="admin-heading"><div><h2>Control centre</h2><p>Manage hostel listings and review student room requests.</p></div><div class="admin-actions"><button class="dark-btn" id="openListingEditor">Edit listings</button><button class="ghost-btn" id="adminLogout">Log out</button></div></div><div class="admin-stats"><div><strong>${stays.length}</strong><span>Total hostels</span></div><div><strong>${stays.filter(stay => stay.verified).length}</strong><span>Verified</span></div><div><strong>${bookings.length}</strong><span>Total bookings</span></div><div><strong>${pending}</strong><span>Pending review</span></div></div><div class="admin-section-title"><h3>Recent bookings</h3><span>${bookings.length ? 'Live student requests' : 'No requests yet'}</span></div><div class="booking-table">${bookings.length ? bookings.slice(0, 8).map(booking => `<div class="booking-row"><div><strong>${booking.student}</strong><small>${booking.email}</small></div><div><strong>${booking.hostel}</strong><small>${booking.city} · ${booking.room}</small></div><div><strong>${booking.moveIn}</strong><small>Move-in date</small></div><span class="status-${booking.status.toLowerCase()}">${booking.status}</span></div>`).join('') : '<div class="admin-empty">Student booking requests will appear here after someone requests a room.</div>'}</div></div>`); document.querySelector('#openListingEditor').addEventListener('click', showAdmin); document.querySelector('#adminLogout').addEventListener('click', () => { localStorage.removeItem('hostelhive-admin'); document.querySelector('#modalBackdrop').hidden = true; document.querySelector('#adminButton').textContent = 'Admin login'; notify('Admin logged out.'); }); }
function showAdmin() { const selected = stays[0]; openModal(`<div class="kicker">HostelHive admin</div><h2>Manage hostel listings.</h2><p>Edit listing details or replace the main property photo. Changes update the live directory on this device.</p><form class="modal-form" id="adminForm"><label><span>Select hostel</span><select name="id" id="adminStaySelect">${stays.map(stay => `<option value="${stay.id}">${stay.name} · ${stay.city}</option>`).join('')}</select></label><input name="name" id="adminName" value="${selected.name}" placeholder="Hostel name" required><div class="admin-fields"><input name="city" id="adminCity" value="${selected.city}" placeholder="City" required><input name="area" id="adminArea" value="${selected.area}" placeholder="Area" required></div><input name="college" id="adminCollege" value="${selected.college}" placeholder="Nearby college" required><div class="admin-fields"><input name="rent" id="adminRent" type="number" min="1000" value="${selected.rent}" placeholder="Monthly rent" required><select name="room" id="adminRoom"><option ${selected.room === 'Single' ? 'selected' : ''}>Single</option><option ${selected.room === 'Double' ? 'selected' : ''}>Double</option><option ${selected.room === 'Triple' ? 'selected' : ''}>Triple</option></select></div><input name="image" id="adminImage" type="url" value="${selected.image}" placeholder="Main photo URL" required><label class="photo-upload"><span>Upload hostel photos</span><input id="adminPhotoFiles" type="file" accept="image/jpeg,image/png,image/webp" multiple><small>Choose multiple images. The first photo becomes the main listing photo.</small></label><div class="admin-photo-grid" id="adminPhotoGrid"></div><input name="tags" id="adminTags" value="${selected.tags.join(', ')}" placeholder="Amenities, comma separated"><textarea name="about" id="adminAbout" placeholder="Hostel description">${selected.about}</textarea><div class="admin-preview" id="adminPreview" style="background-image:url('${selected.image}')"></div><button class="dark-btn">Save listing changes ↗</button></form>`); document.querySelector('#adminStaySelect').addEventListener('change', event => fillAdminForm(Number(event.target.value))); document.querySelector('#adminImage').addEventListener('input', event => { document.querySelector('#adminPreview').style.backgroundImage = `url('${event.target.value}')`; }); document.querySelector('#adminPhotoFiles').addEventListener('change', event => previewAdminPhotos(event.target.files)); }
function previewAdminPhotos(files) { const grid = document.querySelector('#adminPhotoGrid'); grid.innerHTML = ''; [...files].forEach((file, index) => { const reader = new FileReader(); reader.onload = () => { const image = document.createElement('img'); image.src = reader.result; image.alt = `Selected hostel photo ${index + 1}`; grid.append(image); if (index === 0) { document.querySelector('#adminImage').value = reader.result; document.querySelector('#adminPreview').style.backgroundImage = `url('${reader.result}')`; } }; reader.readAsDataURL(file); }); }
function fillAdminForm(id) { const stay = stays.find(item => item.id === id); ['name', 'city', 'area', 'college', 'rent', 'image', 'about'].forEach(field => { document.querySelector(`#admin${field[0].toUpperCase()}${field.slice(1)}`).value = stay[field]; }); document.querySelector('#adminRoom').value = stay.room; document.querySelector('#adminTags').value = stay.tags.join(', '); document.querySelector('#adminPreview').style.backgroundImage = `url('${stay.image}')`; }
function detail(id) { const stay = stays.find(item => item.id === id); openModal(`<div class="eyebrow">${stay.verified ? '● HostelHive verified' : 'Recently added'} · ${stay.city}</div><h2>${stay.name}</h2><p>${stay.area} · ${stay.distance} from ${stay.college} · ★ ${stay.rating} (42 reviews)</p><div class="detail-image" style="background-image:url('${stay.image}')"></div><p>${stay.about}</p><div class="detail-row"><span>Monthly rent</span><b>${money(stay.rent)} / month</b></div><div class="detail-row"><span>Room type</span><b>${stay.room} sharing</b></div><div class="detail-row"><span>Included</span><b>${stay.tags.join(' · ')}</b></div><button class="dark-btn" style="width:100%;margin-top:20px" data-book="${stay.id}">Request this room ↗</button>`); }
function booking(id) { const stay = stays.find(item => item.id === id); openModal(`<div class="eyebrow">Room request</div><h2>Make ${stay.name} yours.</h2><p>Tell the owner a little about your move-in plans.</p><form class="modal-form" id="bookingForm"><select name="room" required><option value="">Choose room type</option><option>${stay.room} sharing · ${money(stay.rent)}</option><option>Double sharing · ${money(stay.rent - 2000)}</option></select><input name="moveIn" type="date" required /><input name="student" placeholder="Your name" required /><input name="email" type="email" placeholder="Email address" required /><textarea name="message" placeholder="Message for the owner (optional)"></textarea><button class="dark-btn">Send room request ↗</button></form>`); document.querySelector('#bookingForm').addEventListener('submit', event => { event.preventDefault(); const form = new FormData(event.target); bookings.unshift({ id: Date.now(), stayId: stay.id, hostel: stay.name, city: stay.city, student: form.get('student'), email: form.get('email'), room: form.get('room'), moveIn: form.get('moveIn'), message: form.get('message'), status: 'Pending' }); localStorage.setItem('hostelhive-bookings', JSON.stringify(bookings)); document.querySelector('#modalBackdrop').hidden = true; notify('Room request sent. The owner will reply soon.'); }); }

document.querySelector('#searchForm').addEventListener('submit', event => { event.preventDefault(); filter(); document.querySelector('#stays').scrollIntoView({ behavior: 'smooth' }); });
['citySelect', 'collegeSelect', 'budgetSelect', 'roomSelect', 'sortSelect'].forEach(id => document.querySelector(`#${id}`).addEventListener('change', filter));
document.querySelector('#queryInput').addEventListener('input', filter);
document.addEventListener('click', event => { const save = event.target.closest('[data-save]'); if (save) { const id = Number(save.dataset.save); saved = saved.includes(id) ? saved.filter(item => item !== id) : [...saved, id]; localStorage.setItem('hostelhive-saved', JSON.stringify(saved)); filter(); notify(saved.includes(id) ? 'Saved to your shortlist' : 'Removed from saved stays'); } const view = event.target.closest('[data-view]'); if (view) detail(Number(view.dataset.view)); const book = event.target.closest('[data-book]'); if (book) booking(Number(book.dataset.book)); const area = event.target.closest('[data-query]'); if (area) { document.querySelector('#queryInput').value = area.dataset.query; filter(); document.querySelector('#stays').scrollIntoView({ behavior: 'smooth' }); } });
document.querySelector('#savedFilter').addEventListener('click', () => { const list = stays.filter(stay => saved.includes(stay.id)); render(list); document.querySelector('#stays').scrollIntoView({ behavior: 'smooth' }); notify(list.length ? 'Showing your saved stays' : 'No saved stays yet'); });
document.querySelector('#clearFilters').addEventListener('click', () => { document.querySelector('#citySelect').value = 'all'; document.querySelector('#collegeSelect').value = 'all'; document.querySelector('#queryInput').value = ''; document.querySelector('#budgetSelect').value = 'all'; document.querySelector('#roomSelect').value = 'all'; activeGender = 'all'; filter(); });
document.querySelector('#viewAll').addEventListener('click', () => { document.querySelector('#queryInput').value = ''; filter(); document.querySelector('#stays').scrollIntoView({ behavior: 'smooth' }); });
document.querySelectorAll('[data-city]').forEach(button => button.addEventListener('click', () => { document.querySelector('#citySelect').value = button.dataset.city; activeGender = 'all'; filter(); document.querySelector('#hostels').scrollIntoView({ behavior: 'smooth' }); }));
document.querySelectorAll('[data-gender]').forEach(button => button.addEventListener('click', () => { activeGender = button.dataset.gender; filter(); document.querySelector('#hostels').scrollIntoView({ behavior: 'smooth' }); }));
document.querySelector('#mapToggle').addEventListener('click', () => notify('Map view is ready for the next release. Try filtering by locality for now.'));
document.querySelector('#modalClose').addEventListener('click', () => { document.querySelector('#modalBackdrop').hidden = true; });
document.querySelector('#modalBackdrop').addEventListener('click', event => { if (event.target.id === 'modalBackdrop') event.currentTarget.hidden = true; });
function showStudentAccount() { const profile = JSON.parse(localStorage.getItem('hostelhive-profile') || '{}'); openModal(`<div class="eyebrow">Student profile</div><h2>Your HostelHive account.</h2><p>Keep your details ready for enquiries, room requests, and bookings.</p><form class="modal-form" id="profileForm"><input name="name" placeholder="Full name" value="${profile.name || ''}" required><input name="age" type="number" min="16" max="60" placeholder="Age" value="${profile.age || ''}" required><input name="phone" type="tel" pattern="[0-9]{10}" title="Enter a 10-digit phone number" placeholder="Phone number" value="${profile.phone || ''}" required><select name="gender" required><option value="">Gender</option><option ${profile.gender === 'Female' ? 'selected' : ''}>Female</option><option ${profile.gender === 'Male' ? 'selected' : ''}>Male</option><option ${profile.gender === 'Non-binary' ? 'selected' : ''}>Non-binary</option><option ${profile.gender === 'Prefer not to say' ? 'selected' : ''}>Prefer not to say</option></select><textarea name="address" placeholder="Current address">${profile.address || ''}</textarea><button class="dark-btn">Save profile ↗</button></form><button class="ghost-btn" id="logoutButton" style="margin-top:14px;width:100%">Log out</button>`); }
document.querySelector('#loginButton').addEventListener('click', () => { if (localStorage.getItem('hostelhive-student')) showStudentAccount(); else window.location.href = 'auth.html'; });
document.querySelector('#listButton').addEventListener('click', () => openModal('<div class="eyebrow">For PG and hostel owners</div><h2>List your PG on HostelHive.</h2><p>Reach students looking for verified rooms in Jaipur and Jodhpur.</p><form class="modal-form" id="ownerForm"><input name="owner" placeholder="Owner name" required><input name="phone" type="tel" placeholder="Mobile number" pattern="[0-9]{10}" title="Enter a 10-digit mobile number" required><input name="property" placeholder="PG or hostel name" required><select name="city" required><option value="">Choose city</option><option>Jaipur</option><option>Jodhpur</option></select><input name="locality" placeholder="Locality (for example, Malviya Nagar)" required><select name="room" required><option value="">Available room type</option><option>Single sharing</option><option>Double sharing</option><option>Triple sharing</option></select><input name="rent" type="number" min="1000" placeholder="Starting monthly rent (₹)" required><textarea name="details" placeholder="Tell students about meals, amenities, and hostel rules"></textarea><button class="dark-btn">Submit for verification ↗</button></form>'));
document.addEventListener('click', event => { if (event.target.id === 'logoutButton') { localStorage.removeItem('hostelhive-student'); localStorage.removeItem('hostelhive-profile'); document.querySelector('#modalBackdrop').hidden = true; document.querySelector('#loginButton').textContent = 'Student login'; notify('You have been logged out.'); } });
document.addEventListener('submit', event => { if (event.target.id === 'loginForm') { event.preventDefault(); const email = event.target.querySelector('input[type="email"]').value; localStorage.setItem('hostelhive-student', email); localStorage.setItem('hostelhive-profile', JSON.stringify({ email })); document.querySelector('#modalBackdrop').hidden = true; document.querySelector('#loginButton').textContent = 'My account'; notify('You are logged in as a student.'); } if (event.target.id === 'adminLoginForm') { event.preventDefault(); const email = event.target.querySelector('[name="email"]').value; localStorage.setItem('hostelhive-admin', email); document.querySelector('#modalBackdrop').hidden = true; document.querySelector('#adminButton').textContent = 'Admin dashboard'; notify('Admin login successful.'); showAdminDashboard(); } if (event.target.id === 'profileForm') { event.preventDefault(); const form = new FormData(event.target); const profile = Object.fromEntries(form.entries()); localStorage.setItem('hostelhive-profile', JSON.stringify(profile)); document.querySelector('#modalBackdrop').hidden = true; notify('Your student profile was saved.'); } if (event.target.id === 'ownerForm') { event.preventDefault(); document.querySelector('#modalBackdrop').hidden = true; notify('PG submitted for HostelHive verification. We will contact you shortly.'); } if (event.target.id === 'adminForm') { event.preventDefault(); const form = new FormData(event.target); const stay = stays.find(item => item.id === Number(form.get('id'))); stay.name = form.get('name'); stay.city = form.get('city'); stay.area = form.get('area'); stay.college = form.get('college'); stay.rent = Number(form.get('rent')); stay.room = form.get('room'); stay.image = form.get('image'); stay.tags = form.get('tags').split(',').map(tag => tag.trim()).filter(Boolean); stay.about = form.get('about'); localStorage.setItem('hostelhive-admin-edits', JSON.stringify(stays)); document.querySelector('#modalBackdrop').hidden = true; filter(); notify(`${stay.name} was updated successfully.`); } });
if (localStorage.getItem('hostelhive-student')) document.querySelector('#loginButton').textContent = 'My account';
render();
