import 'dotenv/config';
import express from 'express';
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import multer from 'multer';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const app = express();
const port = Number(process.env.PORT || 5000);
const mongoUri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/hostelhive';
const jwtSecret = process.env.JWT_SECRET || 'change-this-development-secret';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const uploadDir = path.join(__dirname, 'uploads');
fs.mkdirSync(uploadDir, { recursive: true });

const userSchema = new mongoose.Schema({ name: { type: String, required: true, trim: true }, email: { type: String, required: true, unique: true, lowercase: true, trim: true, index: true }, password: { type: String, required: true, minlength: 6 }, role: { type: String, enum: ['student', 'owner', 'admin'], default: 'student' }, phone: String, age: Number, gender: String, address: String }, { timestamps: true });
const propertySchema = new mongoose.Schema({ name: { type: String, required: true, trim: true }, city: { type: String, enum: ['Jaipur', 'Jodhpur'], required: true, index: true }, area: { type: String, required: true, trim: true, index: true }, college: { type: String, required: true, trim: true, index: true }, rent: { type: Number, required: true, min: 1000 }, deposit: { type: Number, default: 0, min: 0 }, room: { type: String, enum: ['Single', 'Double', 'Triple'], required: true }, gender: { type: String, enum: ['Male', 'Female', 'Unisex'], default: 'Unisex' }, tags: [String], about: String, images: [String], verified: { type: Boolean, default: false }, owner: { type: mongoose.Schema.Types.ObjectId, ref: 'User' } }, { timestamps: true });
propertySchema.index({ city: 1, college: 1, rent: 1 });
const bookingSchema = new mongoose.Schema({ property: { type: mongoose.Schema.Types.ObjectId, ref: 'Property', required: true }, student: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, room: String, moveIn: { type: Date, required: true }, message: String, status: { type: String, enum: ['Pending', 'Approved', 'Confirmed', 'Completed', 'Cancelled'], default: 'Pending' } }, { timestamps: true });
const favoriteSchema = new mongoose.Schema({ student: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, property: { type: mongoose.Schema.Types.ObjectId, ref: 'Property', required: true } }, { timestamps: true });
 favoriteSchema.index({ student: 1, property: 1 }, { unique: true });
const reportSchema = new mongoose.Schema({ property: { type: mongoose.Schema.Types.ObjectId, ref: 'Property', required: true }, student: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, reason: { type: String, required: true, maxlength: 500 }, status: { type: String, enum: ['Open', 'Reviewed', 'Resolved'], default: 'Open' } }, { timestamps: true });
const User = mongoose.model('User', userSchema); const Property = mongoose.model('Property', propertySchema); const Booking = mongoose.model('Booking', bookingSchema); const Favorite = mongoose.model('Favorite', favoriteSchema); const Report = mongoose.model('Report', reportSchema);

const upload = multer({ storage: multer.diskStorage({ destination: uploadDir, filename: (_req, file, cb) => cb(null, `${Date.now()}-${file.originalname.replace(/[^a-zA-Z0-9._-]/g, '')}`) }), limits: { files: 8, fileSize: 5 * 1024 * 1024 }, fileFilter: (_req, file, cb) => cb(null, ['image/jpeg', 'image/png', 'image/webp'].includes(file.mimetype)) });
app.use(helmet()); app.use(cors({ origin: process.env.CLIENT_ORIGIN?.split(',') || true })); app.use(express.json({ limit: '1mb' })); app.use('/uploads', express.static(uploadDir)); app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 300 }));
const sign = user => jwt.sign({ id: user._id, role: user.role, email: user.email }, jwtSecret, { expiresIn: '7d' });
function auth(req, res, next) { try { const token = req.headers.authorization?.replace('Bearer ', ''); if (!token) return res.status(401).json({ message: 'Authentication required' }); req.user = jwt.verify(token, jwtSecret); next(); } catch { res.status(401).json({ message: 'Invalid or expired token' }); } }
const roles = (...allowed) => (req, res, next) => allowed.includes(req.user.role) ? next() : res.status(403).json({ message: 'You do not have permission for this action' });
const safeUser = user => ({ id: user._id, name: user.name, email: user.email, role: user.role, phone: user.phone, age: user.age, gender: user.gender, address: user.address });

app.get('/api/health', (_req, res) => res.json({ ok: true, service: 'HostelHive API' }));
app.post('/api/auth/register', async (req, res, next) => { try { const { name, email, password, role = 'student' } = req.body; if (!name || !email || !password || !['student', 'owner'].includes(role)) return res.status(400).json({ message: 'Name, email, password, and valid role are required' }); if (await User.exists({ email: email.toLowerCase() })) return res.status(409).json({ message: 'Email is already registered' }); const user = await User.create({ name, email, password: await bcrypt.hash(password, 12), role }); res.status(201).json({ token: sign(user), user: safeUser(user) }); } catch (error) { next(error); } });
app.post('/api/auth/login', async (req, res, next) => { try { const user = await User.findOne({ email: req.body.email?.toLowerCase() }); if (!user || !(await bcrypt.compare(req.body.password || '', user.password))) return res.status(401).json({ message: 'Invalid email or password' }); res.json({ token: sign(user), user: safeUser(user) }); } catch (error) { next(error); } });
app.get('/api/auth/me', auth, async (req, res, next) => { try { const user = await User.findById(req.user.id); res.json({ user: safeUser(user) }); } catch (error) { next(error); } });
app.patch('/api/auth/me', auth, async (req, res, next) => { try { const allowed = ['name', 'phone', 'age', 'gender', 'address']; const changes = Object.fromEntries(Object.entries(req.body).filter(([key]) => allowed.includes(key))); const user = await User.findByIdAndUpdate(req.user.id, changes, { new: true, runValidators: true }); res.json({ user: safeUser(user) }); } catch (error) { next(error); } });

app.get('/api/properties', async (req, res, next) => { try { const { city, college, area, q, minRent, maxRent, room, gender, sort = 'rating' } = req.query; const filter = {}; if (city && ['Jaipur', 'Jodhpur'].includes(city)) filter.city = city; if (college) filter.college = new RegExp(`^${college}$`, 'i'); if (area) filter.area = new RegExp(area, 'i'); if (q) filter.$or = ['name', 'area', 'college', 'city'].map(field => ({ [field]: new RegExp(q, 'i') })); if (room) filter.room = room; if (gender) filter.gender = gender; if (minRent || maxRent) filter.rent = { ...(minRent && { $gte: Number(minRent) }), ...(maxRent && { $lte: Number(maxRent) }) }; const sortMap = { rating: { rating: -1, createdAt: -1 }, 'price-low': { rent: 1 }, 'price-high': { rent: -1 }, newest: { createdAt: -1 } }; const properties = await Property.find(filter).sort(sortMap[sort] || sortMap.rating).limit(100).lean(); res.json({ count: properties.length, properties }); } catch (error) { next(error); } });
app.get('/api/properties/:id', async (req, res, next) => { try { const property = await Property.findById(req.params.id).populate('owner', 'name phone'); if (!property) return res.status(404).json({ message: 'Hostel not found' }); res.json({ property }); } catch (error) { next(error); } });
app.post('/api/properties', auth, roles('owner', 'admin'), upload.array('photos', 8), async (req, res, next) => { try { const property = await Property.create({ ...req.body, tags: req.body.tags ? req.body.tags.split(',').map(tag => tag.trim()) : [], images: (req.files || []).map(file => `/uploads/${file.filename}`), owner: req.user.id, verified: req.user.role === 'admin' }); res.status(201).json({ property }); } catch (error) { next(error); } });
app.patch('/api/properties/:id', auth, roles('owner', 'admin'), upload.array('photos', 8), async (req, res, next) => { try { const property = await Property.findById(req.params.id); if (!property) return res.status(404).json({ message: 'Hostel not found' }); if (req.user.role === 'owner' && String(property.owner) !== req.user.id) return res.status(403).json({ message: 'You can only edit your own listings' }); const allowed = ['name', 'city', 'area', 'college', 'rent', 'deposit', 'room', 'gender', 'about']; allowed.forEach(key => { if (req.body[key] !== undefined) property[key] = req.body[key]; }); if (req.body.tags !== undefined) property.tags = req.body.tags.split(',').map(tag => tag.trim()); if (req.files?.length) property.images = [...property.images, ...req.files.map(file => `/uploads/${file.filename}`)]; if (req.user.role === 'admin' && req.body.verified !== undefined) property.verified = req.body.verified === 'true'; await property.save(); res.json({ property }); } catch (error) { next(error); } });
app.delete('/api/properties/:id', auth, roles('owner', 'admin'), async (req, res, next) => { try { const property = await Property.findById(req.params.id); if (!property) return res.status(404).json({ message: 'Hostel not found' }); if (req.user.role === 'owner' && String(property.owner) !== req.user.id) return res.status(403).json({ message: 'You can only delete your own listings' }); await property.deleteOne(); res.status(204).end(); } catch (error) { next(error); } });

app.post('/api/bookings', auth, roles('student'), async (req, res, next) => { try { const { property, room, moveIn, message } = req.body; if (!property || !room || !moveIn) return res.status(400).json({ message: 'Property, room, and move-in date are required' }); const booking = await Booking.create({ property, student: req.user.id, room, moveIn, message }); res.status(201).json({ booking: await booking.populate('property', 'name city area') }); } catch (error) { next(error); } });
app.get('/api/bookings', auth, async (req, res, next) => { try { const filter = req.user.role === 'student' ? { student: req.user.id } : {}; const bookings = await Booking.find(filter).populate('property', 'name city area').populate('student', 'name email phone').sort('-createdAt'); res.json({ bookings }); } catch (error) { next(error); } });
app.patch('/api/bookings/:id/status', auth, roles('owner', 'admin'), async (req, res, next) => { try { if (!['Pending', 'Approved', 'Confirmed', 'Completed', 'Cancelled'].includes(req.body.status)) return res.status(400).json({ message: 'Invalid booking status' }); const booking = await Booking.findByIdAndUpdate(req.params.id, { status: req.body.status }, { new: true }).populate('property', 'name city'); if (!booking) return res.status(404).json({ message: 'Booking not found' }); res.json({ booking }); } catch (error) { next(error); } });
app.post('/api/favorites/:propertyId', auth, roles('student'), async (req, res, next) => { try { await Favorite.findOneAndUpdate({ student: req.user.id, property: req.params.propertyId }, { student: req.user.id, property: req.params.propertyId }, { upsert: true }); res.status(201).json({ saved: true }); } catch (error) { next(error); } });
app.delete('/api/favorites/:propertyId', auth, roles('student'), async (req, res, next) => { try { await Favorite.deleteOne({ student: req.user.id, property: req.params.propertyId }); res.status(204).end(); } catch (error) { next(error); } });
app.get('/api/favorites', auth, roles('student'), async (req, res, next) => { try { const favorites = await Favorite.find({ student: req.user.id }).populate('property'); res.json({ favorites }); } catch (error) { next(error); } });
app.post('/api/reports', auth, roles('student'), async (req, res, next) => { try { const report = await Report.create({ property: req.body.property, student: req.user.id, reason: req.body.reason }); res.status(201).json({ report }); } catch (error) { next(error); } });
app.get('/api/admin/overview', auth, roles('admin'), async (_req, res, next) => { try { const [students, owners, properties, verified, bookings, reports] = await Promise.all([User.countDocuments({ role: 'student' }), User.countDocuments({ role: 'owner' }), Property.countDocuments(), Property.countDocuments({ verified: true }), Booking.countDocuments(), Report.countDocuments({ status: 'Open' })]); res.json({ students, owners, properties, verified, bookings, openReports: reports }); } catch (error) { next(error); } });
app.use((error, _req, res, _next) => { console.error(error); if (error.code === 11000) return res.status(409).json({ message: 'A record with that value already exists' }); res.status(error.status || 500).json({ message: error.message || 'Internal server error' }); });

mongoose.connect(mongoUri).then(() => app.listen(port, () => console.log(`HostelHive API listening on http://localhost:${port}`))).catch(error => { console.error('MongoDB connection failed:', error.message); process.exit(1); });
